### ISSUE TITLE
(Request) This infringes my Charms Bar Port project

### ISSUE THREAD

**Issue by Icepenguins101** [Sub-Bubble/CharmsBarReloaded#1]
Hello, this is the original developer of Charms Bar Port;

I am calling for a DMCA takedown because you stole my idea to bring Charms Bar to Windows 10/11. I appreciate your improvements but you could have just implemented them on my program which is still in hiatus due to my computer breaking completely due to dropping it by mistake during a bad day. A repair station in New York is why Charms Bar Port never got through any updates for two months.

But I have to ask why you stole my idea, my code, and my entire implementation (including the faulty battery/wi-fi code which you could have just forked for my project), rebranded it under a different name, and release it without my permission.

—Jayden Montoya; creator of the Charms Bar Port program

**Comment by Icepenguins101** [comment]
My usage of SystemInformation to get the battery percentage was implemented last year and I get it that the detection icons wasn't quite right, but there's no excuse to clone my implementation. You could've just forked my program with the fixed wi-fi/battery implementation.

**Comment by Sub-Bubble** [comment]
SystemInformation is not an uncommon library to use when getting battery percentage. If you were to use some 3rd party/your own library, than i could agree with you. Plus, I wouldn't consider that this is a fork since I wrote this from scratch.

If you would like to be credited, which is why, as far as my understanding goes, the reason you want to take my repo down, I can provide you with that in a way you'd want to be credited.

**Comment by Icepenguins101** [comment]
I will request to be credited because most of the sources (specifically the image sources) were my doings.

**Comment by Sub-Bubble** [comment]
Sure! I will credit you in README and will send you a preview shortly with credits added to ensure you're ok with the way I have implemented it.

**Comment by Sub-Bubble** [comment]
![credit](https://github.com/Sub-Bubble/CharmsBarReloaded/assets/75545405/b9cd8090-c20c-4bf6-b27c-1ddda7a4fffd)
Here. If this is fine by you, I'm commiting my change.

**Comment by Icepenguins101** [comment]
That's cool.

**Comment by Sub-Bubble** [comment]
Good. The repo should update in a few minutes.
