### ISSUE TITLE
How about adding more buttons to "Settings" panel, like "Power"?

### ISSUE THREAD

**Issue by suntrise** [Sub-Bubble/CharmsBarReloaded#2]
Could you add more buttons to the "Settings" panel, like "Power", like in actual Windows 8?
I am used to shutting down the system via the Charms Bar in Windows 8. It would be nice if I could do the same in Windows 10/11.
![image](https://github.com/user-attachments/assets/9a0e5afb-5690-4b08-9707-866359394f93)

**Comment by Sub-Bubble** [comment]
Hello and thanks for your suggestion!

While there's no eta for this, I will try to add this feature!

**Comment by Sub-Bubble** [comment]
Added in the latest release, [a5.1](https://github.com/Sub-Bubble/CharmsBarReloaded/releases/tag/a5.1).
